import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Luminous Nexus — full token set
        'surface-container-lowest': '#0c0e16',
        'surface-container-low': '#191b24',
        'surface-container': '#1d1f28',
        'surface-container-high': '#282a32',
        'surface-container-highest': '#33343e',
        'surface-dim': '#11131b',
        surface: '#11131b',
        'surface-bright': '#373942',
        'surface-variant': '#33343e',
        'surface-tint': '#00dbe7',
        background: '#11131b',
        'on-background': '#e2e1ee',
        'on-surface': '#e2e1ee',
        'on-surface-variant': '#b9cacb',
        'inverse-surface': '#e2e1ee',
        'inverse-on-surface': '#2e3039',
        outline: '#849495',
        'outline-variant': '#3a494b',
        primary: '#e1fdff',
        'on-primary': '#00363a',
        'primary-container': '#00f2ff',
        'on-primary-container': '#006a71',
        'inverse-primary': '#00696f',
        'primary-fixed': '#74f5ff',
        'primary-fixed-dim': '#00dbe7',
        'on-primary-fixed': '#002022',
        'on-primary-fixed-variant': '#004f54',
        secondary: '#d0bcff',
        'on-secondary': '#3c0091',
        'secondary-container': '#571bc1',
        'on-secondary-container': '#c4abff',
        'secondary-fixed': '#e9ddff',
        'secondary-fixed-dim': '#d0bcff',
        'on-secondary-fixed': '#23005c',
        'on-secondary-fixed-variant': '#5516be',
        tertiary: '#e1ffec',
        'on-tertiary': '#003824',
        'tertiary-container': '#67f4b7',
        'on-tertiary-container': '#006e4b',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        arabic: ['var(--font-arabic)', 'IBM Plex Sans Arabic', 'sans-serif'],
        sans: ['var(--font-arabic)', 'IBM Plex Sans Arabic', 'sans-serif'],
      },
      backgroundImage: {
        'gradient-cyan-violet': 'linear-gradient(135deg, #00dbe7, #571bc1)',
        'gradient-cyan-violet-rtl': 'linear-gradient(225deg, #00dbe7, #571bc1)',
      },
      boxShadow: {
        'glow-cyan': '0 0 20px rgba(0, 219, 231, 0.25)',
        'glow-violet': '0 0 20px rgba(87, 27, 193, 0.25)',
        'glow-emerald': '0 0 20px rgba(103, 244, 183, 0.25)',
        'glow-instagram': '0 8px 20px rgba(225,48,108,0.35)',
        'glow-linkedin': '0 8px 20px rgba(0,119,181,0.35)',
        'glow-facebook': '0 8px 20px rgba(24,119,242,0.35)',
        'glow-whatsapp': '0 8px 20px rgba(37,211,102,0.35)',
      },
      animation: {
        'bounce-slow': 'bounce 2s infinite',
        'pulse-slow': 'pulse 3s infinite',
        'fade-in': 'fadeIn 0.5s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}

export default config
